apiVersion: v1
kind: Service
metadata:
  name: rembg-service
spec:
  selector:
    app: rembg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Exposes externally with a public IP